CREATE DATABASE PROJECT;
USE PROJECT;
SELECT * FROM COVID_19;


-- 1. LOOKING AT TOP 10 COUNTRIES WITH MOST NUMBER OF CASES
SELECT COUNTRY,TOTALCASES FROM COVID_19
ORDER BY TOTALCASES  DESC
LIMIT 10;

-- 2. LOOKING AT TOP 10 COUNTRIES WITH  MOST NUMBER OF DEATHS
SELECT COUNTRY,TOTALDEATHS FROM COVID_19
ORDER BY TOTALDEATHS DESC
LIMIT 10;

-- 3. LOOKING AT TOTAL NUMBER OF CASES AND DEATH IN ALL THE CONTINENTS (FROM MOST TO LEAST)
SELECT CONTINENT,SUM(TOTALCASES) AS TOTALCASE_CONTINENT
FROM COVID_19
GROUP BY CONTINENT
ORDER BY TOTALCASE_CONTINENT DESC;

SELECT CONTINENT,SUM(TOTALDEATHS) AS TOTALDEATHS_CONTINENT
FROM COVID_19
GROUP BY CONTINENT
ORDER BY TOTALDEATHS_CONTINENT DESC;


-- 4. LOOKING AT TOTAL CASES VS TOTAL DEATHS (MORTALITY RATE)
-- SHOWS LIKELYHOOD OF DYING IF YOU CONTACT COVID IN YOUR COUNTRY
SELECT COUNTRY,TOTALCASES,TOTALDEATHS,(TOTALDEATHS/TOTALCASES)*100 AS DEATH_PERCENTAGE
FROM COVID_19
ORDER BY DEATH_PERCENTAGE DESC;


-- 5. LOOKING AT TOTAL NUMBER OF DEATHS IN ALL THE CONTINENTS
-- SHOWS WHICH CONTINENT HAS MOST AND LEAST DEATHS
SELECT CONTINENT,SUM(TOTALDEATHS) AS TOTALDEATHS_CONTINENT
FROM COVID_19
GROUP BY CONTINENT
ORDER BY TOTALDEATHS_CONTINENT DESC;
 
-- 6. LOOKING AT INDIA COVID-19 REPORT
SELECT * FROM COVID_19
WHERE COUNTRY='INDIA';

-- 7. LOOKING AT COUNTRIES WITH  MOST CASES WITH RESPECT TO ITS POPULATION(HIGHEST INFECTION RATE)
-- SHOWS WHAT PERCENT OF POPULATION GOT COVID
SELECT COUNTRY,(TOTALCASES/POPULATION)*100 AS CASES_PER_POPULATION
FROM COVID_19
ORDER BY CASES_PER_POPULATION DESC
LIMIT 5;                         -- (QATAR HAS MOST NUMBER OF CASES WITH RESPECT TO ITS POPULATION OR WE CAN SAY THAT ALMOST 4% OF QATAR PUPULATION WAS AFFECTED BY COVID-19)

-- 8. LOOKING AT COUNTRIES WITH  LEAST CASES WITH RESPECT TO ITS POPULATION (LOWEST INFECTION RATE)
SELECT COUNTRY,(TOTALCASES/POPULATION)*100 AS CASES_PER_POPULATION
FROM COVID_19
ORDER BY CASES_PER_POPULATION 
LIMIT 5;                         -- ANGOLA HAS LEAST CASES WITH RESPECT TO ITS POPULATION(ONLY 0.0025% OF ANGOLAS POPULATION WAS AFFECTED)

-- 9. LOOKING AT INDIA'S DEATH AND CASE PERCENTAGE
SELECT COUNTRY,POPULATION,TOTALCASES,TOTALDEATHS,(TOTALDEATHS/TOTALCASES)*100 AS DEATH_PERCENTAGE,(TOTALCASES/POPULATION)*100 AS CASE_PERCENTAGE
FROM COVID_19
WHERE COUNTRY='INDIA';

-- 10. SHOWING COUNTRIES IN ASIA AND EUROPE WITH HIGHEST AND LOWEST DEATH COUNT PER POPULATION 
-- DEATH RATE OF COUNTRIES IN ASIA AND EUROPE
SELECT COUNTRY,CONTINENT,POPULATION,TOTALDEATHS,(TOTALDEATHS/POPULATION)*100 AS DEATH_RATE
FROM COVID_19
WHERE CONTINENT IN ('ASIA','EUROPE')
ORDER BY DEATH_RATE DESC;

SELECT COUNTRY,CONTINENT,POPULATION,TOTALDEATHS,(TOTALDEATHS/POPULATION)*100 AS HIGHEST_DEATHCOUNT
FROM COVID_19
WHERE CONTINENT IN ('ASIA','EUROPE')
ORDER BY HIGHEST_DEATHCOUNT;

-- 11. TO SHOW GLOBAL DEATH PERCENTAGE 
SELECT SUM(TOTALCASES)AS TOTAL_CASES,SUM(TOTALDEATHS) AS TOTAL_DEATHS,(SUM(TOTALDEATHS)/SUM(TOTALCASES))* 100 AS GLOBAL_DEATH_PERCEBTAGE
FROM COVID_19;

-- 12. TO SHOW INFECTED POPULATION PERCENTAGE GLOBALLY
-- 0.36 PERCENT OF GLOBAL POLATION WAS INFECTED BY COVID
SELECT SUM(POPULATION) AS GLOBAL_POP,SUM(TOTALCASES) AS TOTAL_GLOBALCASES,(SUM(TOTALCASES)/SUM(POPULATION))*100 AS INFECTED_POP_PERCENTAGE
FROM COVID_19;

-- 13. HOW MANY DIFFRENT WHO(WORLD HEALTH ORG.)REGIONS ARE THERE?
SELECT DISTINCT WHO_REGION
FROM COVID_19;

SELECT WHO_REGION,SUM(TOTALCASES),SUM(TOTALDEATHS)
FROM COVID_19
WHERE WHO_REGION='SOUTH-EASTASIA'
GROUP BY WHO_REGION;
